"""Core module for PyUT Agent.

This module contains the core components that are shared across the application:
- Unified retry management
- Unified error recovery
- Unified configuration management
- Dependency injection container
- Abstract base classes and protocols
- Application context for global state management
"""

from .retry_manager import (
    RetryManager,
    RetryConfig,
    RetryStrategy,
    RetryResult,
    InfiniteRetryManager,
    with_retry,
    create_retry_manager,
    AsyncRetryWithBackoff,
)
from .error_recovery import (
    ErrorRecoveryManager,
    ErrorCategory,
    RecoveryStrategy,
    RecoveryResult,
    ErrorClassifier,
    StatePreserver,
    is_retryable_error,
)
from .cache import FileCache, Memoize
from .security import (
    SecurityError,
    PathValidator,
    SensitiveField,
    CommandBuilder,
    sanitize_for_display,
    validate_maven_project,
)
from .secure_logging import SecureLogger as SecureLogger
from .config import (
    Settings,
    LLMConfig,
    LLMConfigCollection,
    LLMProvider,
    AiderConfig,
    ArchitectMode,
    ProjectPaths,
    CoverageSettings,
    get_settings,
    get_data_dir,
    get_llm_config_path,
    get_aider_config_path,
    get_app_config_path,
    load_llm_config,
    save_llm_config,
    load_aider_config,
    save_aider_config,
    load_app_config,
    save_app_config,
    get_default_endpoint,
    get_available_models,
)
from .container import Container, get_container, configure_container
from .context import ApplicationContext, get_context, reset_context, initialize_context
from .events import (
    EventType,
    AgentEvent,
    EventEmitter,
    EventSubscriber,
    get_event_emitter,
    reset_event_emitter,
)
from .protocols import (
    LLMClientProtocol,
    CodeEditorProtocol,
    TestRunnerProtocol,
    CodeParserProtocol,
    MemoryProtocol,
    RecoveryHandlerProtocol,
    AgentState,
    AgentResult,
    TestResult,
    CoverageResult,
    ParsedCode,
    ClassInfo,
    MethodInfo,
    FieldInfo,
    ParameterInfo,
    ErrorAnalysis,
    RecoveryAction,
    BaseAgent,
    BaseTool,
)

__all__ = [
    "RetryManager",
    "RetryConfig",
    "RetryStrategy",
    "RetryResult",
    "InfiniteRetryManager",
    "with_retry",
    "create_retry_manager",
    "AsyncRetryWithBackoff",
    "ErrorRecoveryManager",
    "ErrorCategory",
    "RecoveryStrategy",
    "RecoveryResult",
    "ErrorClassifier",
    "StatePreserver",
    "is_retryable_error",
    "FileCache",
    "Memoize",
    "SecurityError",
    "PathValidator",
    "SensitiveField",
    "SecureLogger",
    "CommandBuilder",
    "sanitize_for_display",
    "validate_maven_project",
    "Settings",
    "LLMConfig",
    "LLMConfigCollection",
    "LLMProvider",
    "AiderConfig",
    "ArchitectMode",
    "ProjectPaths",
    "CoverageSettings",
    "get_settings",
    "get_data_dir",
    "get_llm_config_path",
    "get_aider_config_path",
    "get_app_config_path",
    "load_llm_config",
    "save_llm_config",
    "load_aider_config",
    "save_aider_config",
    "load_app_config",
    "save_app_config",
    "get_default_endpoint",
    "get_available_models",
    "Container",
    "get_container",
    "configure_container",
    "ApplicationContext",
    "get_context",
    "reset_context",
    "initialize_context",
    "EventType",
    "AgentEvent",
    "EventEmitter",
    "EventSubscriber",
    "get_event_emitter",
    "reset_event_emitter",
    "LLMClientProtocol",
    "CodeEditorProtocol",
    "TestRunnerProtocol",
    "CodeParserProtocol",
    "MemoryProtocol",
    "RecoveryHandlerProtocol",
    "AgentState",
    "AgentResult",
    "TestResult",
    "CoverageResult",
    "ParsedCode",
    "ClassInfo",
    "MethodInfo",
    "FieldInfo",
    "ParameterInfo",
    "ErrorAnalysis",
    "RecoveryAction",
    "BaseAgent",
    "BaseTool",
]
