"""Enhanced Autonomous Loop - LLM-powered Observe-Think-Act-Verify-Learn cycle.

This module enhances the autonomous loop with:
- LLM-based deep reasoning for decision making
- Dynamic tool selection based on context
- Self-correction and recovery mechanisms
- Learning from execution history
"""

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Set

from .autonomous_loop import (
    LoopState,
    Observation,
    Thought,
    Action,
    Verification,
    LoopResult,
    AutonomousLoop
)
from .tool_service import AgentToolService

logger = logging.getLogger(__name__)


class DecisionStrategy(Enum):
    """Strategies for making decisions."""
    RULE_BASED = auto()      # Use predefined rules
    LLM_BASED = auto()       # Use LLM reasoning
    HYBRID = auto()          # Combine rules and LLM
    ADAPTIVE = auto()        # Adapt based on success rate


@dataclass
class ExecutionContext:
    """Rich execution context for decision making."""
    task: str
    iteration: int
    max_iterations: int
    observations: List[Observation]
    thoughts: List[Thought]
    actions_taken: List[Dict[str, Any]]
    available_tools: List[str]
    tool_descriptions: Dict[str, str]
    previous_errors: List[str] = field(default_factory=list)
    successful_patterns: List[str] = field(default_factory=list)


@dataclass
class LLMThought:
    """Thought generated by LLM."""
    reasoning: str
    decision: str
    confidence: float
    plan: List[Dict[str, Any]]
    tool_recommendations: List[str] = field(default_factory=list)
    risk_assessment: str = ""
    alternative_approaches: List[str] = field(default_factory=list)


@dataclass
class LearningEntry:
    """Entry in the learning history."""
    timestamp: datetime
    situation: str
    action_taken: str
    outcome: str
    lesson: str
    success: bool


class EnhancedAutonomousLoop(AutonomousLoop):
    """Enhanced autonomous loop with LLM-powered reasoning.
    
    Enhancements over base AutonomousLoop:
    1. LLM-based thinking with deep reasoning
    2. Dynamic tool selection from available tools
    3. Self-correction based on error patterns
    4. Learning from execution history
    5. Adaptive decision strategy
    """
    
    def __init__(
        self,
        tool_service: AgentToolService,
        llm_client: Any,
        max_iterations: int = 10,
        confidence_threshold: float = 0.8,
        user_interruptible: bool = True,
        decision_strategy: DecisionStrategy = DecisionStrategy.HYBRID,
        enable_self_correction: bool = True
    ):
        """Initialize enhanced autonomous loop.
        
        Args:
            tool_service: Tool service for executing tools
            llm_client: LLM client for reasoning
            max_iterations: Maximum iterations before stopping
            confidence_threshold: Confidence threshold to consider task complete
            user_interruptible: Whether user can interrupt the loop
            decision_strategy: Strategy for making decisions
            enable_self_correction: Whether to enable self-correction
        """
        super().__init__(
            tool_service=tool_service,
            max_iterations=max_iterations,
            confidence_threshold=confidence_threshold,
            user_interruptible=user_interruptible
        )
        
        self.llm_client = llm_client
        self.decision_strategy = decision_strategy
        self.enable_self_correction = enable_self_correction
        
        # Learning history
        self._learning_history: List[LearningEntry] = []
        self._tool_success_rates: Dict[str, Dict[str, Any]] = {}
        
        # Error tracking for self-correction
        self._error_patterns: Dict[str, int] = {}
        self._recovery_attempts: int = 0
        self._max_recovery_attempts: int = 3
        
        logger.info(f"[EnhancedAutonomousLoop] Initialized with strategy: {decision_strategy.name}")
    
    async def _think(
        self,
        task: str,
        observation: Observation,
        context: Dict[str, Any]
    ) -> Thought:
        """Think about the next action using LLM-based reasoning.
        
        Args:
            task: Current task
            observation: Current observation
            context: Current context
        
        Returns:
            Thought with plan
        """
        logger.debug(f"[EnhancedAutonomousLoop] Thinking - iteration {self._iteration}")
        
        # Build execution context
        exec_context = ExecutionContext(
            task=task,
            iteration=self._iteration,
            max_iterations=self.max_iterations,
            observations=self._observations[-5:],  # Last 5 observations
            thoughts=self._thoughts[-3:],  # Last 3 thoughts
            actions_taken=self._actions_taken,
            available_tools=self.tool_service.list_available_tools(),
            tool_descriptions=self._get_tool_descriptions(),
            previous_errors=self._get_recent_errors(),
            successful_patterns=self._get_successful_patterns()
        )
        
        # Choose decision strategy
        if self.decision_strategy == DecisionStrategy.RULE_BASED:
            return await self._think_rule_based(exec_context)
        elif self.decision_strategy == DecisionStrategy.LLM_BASED:
            return await self._think_llm_based(exec_context)
        elif self.decision_strategy == DecisionStrategy.ADAPTIVE:
            return await self._think_adaptive(exec_context)
        else:  # HYBRID
            return await self._think_hybrid(exec_context)
    
    async def _think_llm_based(self, context: ExecutionContext) -> Thought:
        """Use LLM for deep reasoning.
        
        Args:
            context: Execution context
            
        Returns:
            Thought with LLM-generated plan
        """
        prompt = self._build_thinking_prompt(context)
        
        try:
            response = await self.llm_client.chat(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3
            )
            
            content = response.content if hasattr(response, 'content') else str(response)
            llm_thought = self._parse_llm_thought(content)
            
            # Validate and sanitize the plan
            plan = self._validate_plan(llm_thought.plan, context.available_tools)
            
            # Adjust confidence based on iteration
            adjusted_confidence = self._adjust_confidence(
                llm_thought.confidence,
                context.iteration,
                len(context.previous_errors)
            )
            
            logger.info(f"[EnhancedAutonomousLoop] LLM decision: {llm_thought.decision[:100]}...")
            
            return Thought(
                timestamp=datetime.now(),
                reasoning=llm_thought.reasoning,
                decision=llm_thought.decision,
                confidence=adjusted_confidence,
                plan=plan
            )
            
        except Exception as e:
            logger.error(f"[EnhancedAutonomousLoop] LLM thinking failed: {e}")
            # Fallback to rule-based
            return await self._think_rule_based(context)
    
    async def _think_rule_based(self, context: ExecutionContext) -> Thought:
        """Use rule-based thinking as fallback.
        
        Args:
            context: Execution context
            
        Returns:
            Thought with rule-based plan
        """
        # Simple rule-based logic
        task_lower = context.task.lower()
        
        # Check for specific task patterns
        if any(word in task_lower for word in ["test", "testing", "coverage"]):
            plan = self._build_test_plan(context)
            reasoning = "Task involves testing, using test generation workflow"
            confidence = 0.7
        elif any(word in task_lower for word in ["fix", "bug", "error"]):
            plan = self._build_debug_plan(context)
            reasoning = "Task involves debugging, using diagnostic workflow"
            confidence = 0.6
        elif any(word in task_lower for word in ["refactor", "clean", "improve"]):
            plan = self._build_refactor_plan(context)
            reasoning = "Task involves refactoring, using code improvement workflow"
            confidence = 0.7
        else:
            plan = self._build_generic_plan(context)
            reasoning = "Using generic exploration workflow"
            confidence = 0.5
        
        return Thought(
            timestamp=datetime.now(),
            reasoning=reasoning,
            decision=f"Execute {len(plan)} actions based on rules",
            confidence=confidence,
            plan=plan
        )
    
    async def _think_hybrid(self, context: ExecutionContext) -> Thought:
        """Combine LLM and rule-based thinking.
        
        Args:
            context: Execution context
            
        Returns:
            Thought with hybrid plan
        """
        # Try LLM first
        try:
            llm_thought = await self._think_llm_based(context)
            
            # If LLM confidence is low, blend with rules
            if llm_thought.confidence < 0.6:
                rule_thought = await self._think_rule_based(context)
                
                # Merge plans
                combined_plan = self._merge_plans(llm_thought.plan, rule_thought.plan)
                
                return Thought(
                    timestamp=datetime.now(),
                    reasoning=f"LLM: {llm_thought.reasoning} | Rules: {rule_thought.reasoning}",
                    decision="Hybrid approach combining LLM and rule-based insights",
                    confidence=max(llm_thought.confidence, rule_thought.confidence),
                    plan=combined_plan
                )
            
            return llm_thought
            
        except Exception:
            # Fallback to rules
            return await self._think_rule_based(context)
    
    async def _think_adaptive(self, context: ExecutionContext) -> Thought:
        """Adapt strategy based on past performance.
        
        Args:
            context: Execution context
            
        Returns:
            Thought with adaptively chosen plan
        """
        # Calculate success rates
        llm_success_rate = self._calculate_strategy_success_rate("llm")
        rule_success_rate = self._calculate_strategy_success_rate("rule")
        
        # Choose strategy based on success rates
        if llm_success_rate > rule_success_rate + 0.1:
            logger.debug("[EnhancedAutonomousLoop] Choosing LLM strategy (higher success rate)")
            thought = await self._think_llm_based(context)
            thought.decision = f"[Adaptive-LLM] {thought.decision}"
        elif rule_success_rate > llm_success_rate + 0.1:
            logger.debug("[EnhancedAutonomousLoop] Choosing rule strategy (higher success rate)")
            thought = await self._think_rule_based(context)
            thought.decision = f"[Adaptive-Rule] {thought.decision}"
        else:
            # Similar rates, use hybrid
            thought = await self._think_hybrid(context)
            thought.decision = f"[Adaptive-Hybrid] {thought.decision}"
        
        return thought
    
    async def _act(self, action_plan: Dict[str, Any], context: Dict[str, Any]) -> Any:
        """Execute an action with error handling and recovery.
        
        Args:
            action_plan: Action to execute
            context: Current context
        
        Returns:
            Action result
        """
        tool_name = action_plan.get("tool_name")
        parameters = action_plan.get("parameters", {})
        
        logger.debug(f"[EnhancedAutonomousLoop] Acting - executing {tool_name}")
        
        try:
            result = await self.tool_service.execute_tool(tool_name, parameters)
            
            # Track success
            self._track_tool_result(tool_name, result)
            
            # If failed and self-correction enabled, try recovery
            if not getattr(result, 'success', True) and self.enable_self_correction:
                if self._recovery_attempts < self._max_recovery_attempts:
                    recovery_result = await self._attempt_recovery(
                        action_plan, result, context
                    )
                    if recovery_result:
                        return recovery_result
            
            return result
            
        except Exception as e:
            logger.error(f"[EnhancedAutonomousLoop] Action failed: {e}")
            from ..tools.tool import ToolResult
            
            error_result = ToolResult(success=False, error=str(e))
            
            # Track error pattern
            self._track_error(str(e))
            
            return error_result
    
    async def _attempt_recovery(
        self,
        failed_action: Dict[str, Any],
        error_result: Any,
        context: Dict[str, Any]
    ) -> Optional[Any]:
        """Attempt to recover from a failed action.
        
        Args:
            failed_action: The action that failed
            error_result: The error result
            context: Current context
            
        Returns:
            Recovery result if successful, None otherwise
        """
        self._recovery_attempts += 1
        error_msg = str(getattr(error_result, 'error', ''))
        
        logger.info(f"[EnhancedAutonomousLoop] Attempting recovery ({self._recovery_attempts}/{self._max_recovery_attempts})")
        
        # Analyze error and choose recovery strategy
        recovery_plan = self._determine_recovery_strategy(failed_action, error_msg)
        
        if recovery_plan:
            try:
                result = await self.tool_service.execute_tool(
                    recovery_plan["tool_name"],
                    recovery_plan["parameters"]
                )
                
                if getattr(result, 'success', False):
                    logger.info("[EnhancedAutonomousLoop] Recovery successful")
                    self._learning_history.append(LearningEntry(
                        timestamp=datetime.now(),
                        situation=f"Tool {failed_action.get('tool_name')} failed with: {error_msg[:100]}",
                        action_taken=f"Recovery using {recovery_plan['tool_name']}",
                        outcome="Success",
                        lesson=f"Recovery strategy for {error_msg[:50]}",
                        success=True
                    ))
                    return result
                    
            except Exception as e:
                logger.error(f"[EnhancedAutonomousLoop] Recovery failed: {e}")
        
        return None
    
    async def _learn(self, task: str, context: Dict[str, Any]):
        """Learn from current iteration with enhanced tracking.
        
        Args:
            task: Current task
            context: Current context
        """
        logger.debug(f"[EnhancedAutonomousLoop] Learning - iteration {self._iteration}")
        
        if not self._actions_taken:
            return
        
        last_action = self._actions_taken[-1]
        tool_name = last_action.get("tool")
        result = last_action.get("result", {})
        
        # Determine success
        success = False
        if isinstance(result, dict):
            success = result.get('success', False)
        elif hasattr(result, 'success'):
            success = result.success
        
        # Create learning entry
        entry = LearningEntry(
            timestamp=datetime.now(),
            situation=f"Iteration {self._iteration} of task: {task[:100]}",
            action_taken=f"Used {tool_name}",
            outcome="Success" if success else "Failure",
            lesson=self._extract_lesson(tool_name, success, result),
            success=success
        )
        
        self._learning_history.append(entry)
        
        # Update strategy success rates
        self._update_strategy_success_rate(success)
        
        # Call parent learning
        await super()._learn(task, context)
    
    def _build_thinking_prompt(self, context: ExecutionContext) -> str:
        """Build prompt for LLM thinking.
        
        Args:
            context: Execution context
            
        Returns:
            Formatted prompt
        """
        # Build action history
        action_history = "\n".join([
            f"- {a.get('tool')}: {'Success' if isinstance(a.get('result'), dict) and a.get('result', {}).get('success') else 'Failed'}"
            for a in context.actions_taken[-5:]
        ])
        
        # Build available tools
        tools_info = "\n".join([
            f"- {name}: {desc}"
            for name, desc in context.tool_descriptions.items()
        ])
        
        # Build errors
        errors_info = "\n".join([f"- {e}" for e in context.previous_errors[-3:]]) if context.previous_errors else "None"
        
        prompt = f"""You are an autonomous coding agent. Analyze the current situation and decide the next action.

## Task
{context.task}

## Progress
- Iteration: {context.iteration}/{context.max_iterations}
- Previous Actions:
{action_history}

## Recent Errors
{errors_info}

## Available Tools
{tools_info}

## Instructions
1. Analyze the task and progress so far
2. Consider what went wrong in previous attempts (if any)
3. Choose the most appropriate next action
4. Provide your reasoning and confidence level (0.0-1.0)

## Response Format
Return JSON with:
{{
    "reasoning": "Your detailed analysis and reasoning",
    "decision": "Brief description of what you decided to do",
    "confidence": 0.8,
    "plan": [
        {{
            "tool_name": "name_of_tool",
            "parameters": {{"param": "value"}},
            "expected_outcome": "What you expect to achieve"
        }}
    ],
    "risk_assessment": "Potential risks or issues",
    "alternative_approaches": ["Alternative if this fails"]
}}

## Your Analysis:"""
        
        return prompt
    
    def _parse_llm_thought(self, content: str) -> LLMThought:
        """Parse LLM response into LLMThought.
        
        Args:
            content: LLM response content
            
        Returns:
            Parsed LLMThought
        """
        try:
            # Extract JSON
            start = content.find('{')
            end = content.rfind('}')
            
            if start != -1 and end != -1:
                json_str = content[start:end+1]
                data = json.loads(json_str)
                
                return LLMThought(
                    reasoning=data.get("reasoning", "No reasoning provided"),
                    decision=data.get("decision", "No decision made"),
                    confidence=float(data.get("confidence", 0.5)),
                    plan=data.get("plan", []),
                    risk_assessment=data.get("risk_assessment", ""),
                    alternative_approaches=data.get("alternative_approaches", [])
                )
        except json.JSONDecodeError as e:
            logger.warning(f"[EnhancedAutonomousLoop] Failed to parse LLM response: {e}")
        
        # Return default if parsing fails
        return LLMThought(
            reasoning="Failed to parse LLM response",
            decision="Use default approach",
            confidence=0.3,
            plan=[],
            risk_assessment="Parsing error",
            alternative_approaches=["Retry with different prompt"]
        )
    
    def _validate_plan(
        self,
        plan: List[Dict[str, Any]],
        available_tools: List[str]
    ) -> List[Dict[str, Any]]:
        """Validate and sanitize plan.
        
        Args:
            plan: Proposed plan
            available_tools: Available tools
            
        Returns:
            Validated plan
        """
        validated = []
        
        for action in plan:
            tool_name = action.get("tool_name")
            
            # Check if tool is available
            if tool_name not in available_tools:
                logger.warning(f"[EnhancedAutonomousLoop] Tool not available: {tool_name}")
                continue
            
            # Sanitize parameters
            parameters = action.get("parameters", {})
            if not isinstance(parameters, dict):
                parameters = {}
            
            validated.append({
                "tool_name": tool_name,
                "parameters": parameters,
                "expected_outcome": action.get("expected_outcome", "")
            })
        
        return validated
    
    def _adjust_confidence(
        self,
        base_confidence: float,
        iteration: int,
        error_count: int
    ) -> float:
        """Adjust confidence based on context.
        
        Args:
            base_confidence: Base confidence from LLM
            iteration: Current iteration
            error_count: Number of recent errors
            
        Returns:
            Adjusted confidence
        """
        adjusted = base_confidence
        
        # Reduce confidence if many errors
        adjusted -= error_count * 0.1
        
        # Reduce confidence if many iterations
        if iteration > self.max_iterations * 0.7:
            adjusted -= 0.1
        
        # Clamp to [0, 1]
        return max(0.0, min(1.0, adjusted))
    
    def _get_tool_descriptions(self) -> Dict[str, str]:
        """Get descriptions of available tools."""
        descriptions = {}
        
        for tool_name in self.tool_service.list_available_tools():
            try:
                tool = self.tool_service.get_tool(tool_name)
                if tool and hasattr(tool, 'definition'):
                    descriptions[tool_name] = tool.definition.description
                else:
                    descriptions[tool_name] = "No description available"
            except Exception:
                descriptions[tool_name] = "No description available"
        
        return descriptions
    
    def _get_recent_errors(self) -> List[str]:
        """Get recent error messages."""
        errors = []
        
        for action in self._actions_taken[-5:]:
            result = action.get("result", {})
            if isinstance(result, dict) and not result.get("success", True):
                error = result.get("error", "Unknown error")
                errors.append(error[:200])
        
        return errors
    
    def _get_successful_patterns(self) -> List[str]:
        """Get patterns from successful actions."""
        patterns = []
        
        for entry in self._learning_history[-10:]:
            if entry.success:
                patterns.append(f"{entry.action_taken} -> {entry.lesson}")
        
        return patterns
    
    def _build_test_plan(self, context: ExecutionContext) -> List[Dict[str, Any]]:
        """Build plan for testing tasks."""
        return [
            {
                "tool_name": "glob",
                "parameters": {"pattern": "**/*.java"},
                "expected_outcome": "Find Java source files"
            },
            {
                "tool_name": "git_status",
                "parameters": {},
                "expected_outcome": "Check repository status"
            }
        ]
    
    def _build_debug_plan(self, context: ExecutionContext) -> List[Dict[str, Any]]:
        """Build plan for debugging tasks."""
        return [
            {
                "tool_name": "git_status",
                "parameters": {},
                "expected_outcome": "Check what files have changed"
            },
            {
                "tool_name": "git_diff",
                "parameters": {},
                "expected_outcome": "See recent changes"
            }
        ]
    
    def _build_refactor_plan(self, context: ExecutionContext) -> List[Dict[str, Any]]:
        """Build plan for refactoring tasks."""
        return [
            {
                "tool_name": "glob",
                "parameters": {"pattern": "**/*.py"},
                "expected_outcome": "Find Python files to refactor"
            },
            {
                "tool_name": "git_status",
                "parameters": {},
                "expected_outcome": "Check current state before changes"
            }
        ]
    
    def _build_generic_plan(self, context: ExecutionContext) -> List[Dict[str, Any]]:
        """Build generic exploration plan."""
        return [
            {
                "tool_name": "git_status",
                "parameters": {},
                "expected_outcome": "Understand current repository state"
            }
        ]
    
    def _merge_plans(
        self,
        llm_plan: List[Dict[str, Any]],
        rule_plan: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Merge LLM and rule-based plans."""
        # Use LLM plan as primary, add rule plan as fallback
        merged = llm_plan.copy()
        
        # Add rule-based actions that aren't in LLM plan
        llm_tools = {a.get("tool_name") for a in llm_plan}
        for action in rule_plan:
            if action.get("tool_name") not in llm_tools:
                merged.append(action)
        
        return merged[:5]  # Limit to 5 actions
    
    def _determine_recovery_strategy(
        self,
        failed_action: Dict[str, Any],
        error_msg: str
    ) -> Optional[Dict[str, Any]]:
        """Determine recovery strategy based on error."""
        error_lower = error_msg.lower()
        
        # File not found errors
        if "not found" in error_lower or "no such file" in error_lower:
            return {
                "tool_name": "glob",
                "parameters": {"pattern": "**/*"},
                "expected_outcome": "Find available files"
            }
        
        # Permission errors
        if "permission" in error_lower or "access denied" in error_lower:
            return {
                "tool_name": "bash",
                "parameters": {"command": "ls -la"},
                "expected_outcome": "Check permissions"
            }
        
        # Syntax/compilation errors
        if "syntax" in error_lower or "compile" in error_lower:
            return {
                "tool_name": "read_file",
                "parameters": {"file_path": failed_action.get("parameters", {}).get("file_path", "")},
                "expected_outcome": "Read file to identify syntax issue"
            }
        
        return None
    
    def _track_tool_result(self, tool_name: str, result: Any):
        """Track tool execution result."""
        if tool_name not in self._tool_success_rates:
            self._tool_success_rates[tool_name] = {
                "successes": 0,
                "failures": 0,
                "total": 0
            }
        
        success = getattr(result, 'success', True)
        self._tool_success_rates[tool_name]["total"] += 1
        
        if success:
            self._tool_success_rates[tool_name]["successes"] += 1
        else:
            self._tool_success_rates[tool_name]["failures"] += 1
    
    def _track_error(self, error_msg: str):
        """Track error pattern."""
        # Extract error type
        error_type = error_msg.split(":")[0] if ":" in error_msg else error_msg[:50]
        
        self._error_patterns[error_type] = self._error_patterns.get(error_type, 0) + 1
    
    def _extract_lesson(self, tool_name: str, success: bool, result: Any) -> str:
        """Extract lesson from action result."""
        if success:
            return f"{tool_name} was effective for this task"
        else:
            error = str(getattr(result, 'error', 'Unknown error'))[:100]
            return f"{tool_name} failed: {error}"
    
    def _update_strategy_success_rate(self, success: bool):
        """Update strategy success rate."""
        strategy_key = f"strategy_{self.decision_strategy.name}"
        
        if strategy_key not in self._tool_success_rates:
            self._tool_success_rates[strategy_key] = {
                "successes": 0,
                "failures": 0,
                "total": 0
            }
        
        self._tool_success_rates[strategy_key]["total"] += 1
        if success:
            self._tool_success_rates[strategy_key]["successes"] += 1
        else:
            self._tool_success_rates[strategy_key]["failures"] += 1
    
    def _calculate_strategy_success_rate(self, strategy: str) -> float:
        """Calculate success rate for a strategy."""
        key = f"strategy_{strategy.upper()}"
        stats = self._tool_success_rates.get(key, {})
        
        total = stats.get("total", 0)
        successes = stats.get("successes", 0)
        
        if total == 0:
            return 0.5  # Default neutral rate
        
        return successes / total
    
    def get_learning_summary(self) -> Dict[str, Any]:
        """Get summary of learning history."""
        total_entries = len(self._learning_history)
        successful_entries = sum(1 for e in self._learning_history if e.success)
        
        return {
            "total_learnings": total_entries,
            "success_rate": successful_entries / total_entries if total_entries > 0 else 0,
            "tool_success_rates": self._tool_success_rates,
            "error_patterns": self._error_patterns,
            "recent_lessons": [
                {
                    "situation": e.situation[:100],
                    "lesson": e.lesson[:100],
                    "success": e.success
                }
                for e in self._learning_history[-5:]
            ]
        }


def create_enhanced_autonomous_loop(
    tool_service: AgentToolService,
    llm_client: Any,
    max_iterations: int = 10,
    confidence_threshold: float = 0.8,
    decision_strategy: DecisionStrategy = DecisionStrategy.HYBRID
) -> EnhancedAutonomousLoop:
    """Factory function to create EnhancedAutonomousLoop.
    
    Args:
        tool_service: Tool service for execution
        llm_client: LLM client for reasoning
        max_iterations: Maximum iterations
        confidence_threshold: Confidence threshold
        decision_strategy: Decision strategy
        
    Returns:
        EnhancedAutonomousLoop instance
    """
    return EnhancedAutonomousLoop(
        tool_service=tool_service,
        llm_client=llm_client,
        max_iterations=max_iterations,
        confidence_threshold=confidence_threshold,
        decision_strategy=decision_strategy
    )
